#!/bin/bash
#==
#   NOTE      - backupd
#   Author    - Aru
#
#   Created   - 2024.11.27
#   Github    - https://github.com/aruyu
#   Contact   - vine9151@gmail.com
#/



T_CO_RED='\e[1;31m'
T_CO_YELLOW='\e[1;33m'
T_CO_GREEN='\e[1;32m'
T_CO_BLUE='\e[1;34m'
T_CO_GRAY='\e[1;30m'
T_CO_NC='\e[0m'

CURRENT_PROGRESS=0

function script_print()
{
  echo -ne "${T_CO_BLUE}[SCRIPT]${T_CO_NC}$1"
}

function script_notify_print()
{
  echo -ne "${T_CO_BLUE}[SCRIPT]${T_CO_NC}${T_CO_GREEN}-Notify- $1${T_CO_NC}"
}

function script_error_print()
{
  echo -ne "${T_CO_BLUE}[SCRIPT]${T_CO_NC}${T_CO_RED}-Error- $1${T_CO_NC}"
}

function script_println()
{
  echo -ne "${T_CO_BLUE}[SCRIPT]${T_CO_NC}$1\n"
}

function script_notify_println()
{
  echo -ne "${T_CO_BLUE}[SCRIPT]${T_CO_NC}${T_CO_GREEN}-Notify- $1${T_CO_NC}\n"
}

function script_error_println()
{
  echo -ne "${T_CO_BLUE}[SCRIPT]${T_CO_NC}${T_CO_RED}-Error- $1${T_CO_NC}\n"
}

function error_exit()
{
  script_error_println "$1\n"
  exit 1
}

function change_own_mod()
{
  chown root:root $1/*
  chmod 600 $1/*
}

function backup_database()
{
  docker exec -it ${container_name} gitlab-rake gitlab:backup:create
  change_own_mod ${backups}
  mv ${backups}/* ${backup_directory}/
}




#==
#   Starting codes in blew
#/

if [[ $EUID -ne 0 ]]; then
  error_exit "This script must be run as ROOT!"
fi




container_name=$(awk '/^name/{print $3}' /backup/backup.d/default.conf)
backups=$(awk '/^backups/{print $3}' /backup/backup.d/default.conf)
directory=$(awk '/^directory/{print $3}' /backup/backup.d/default.conf)


while true; do
  directory_month=`date +%Y_%m`
  backup_date=`date +%m%d_%H_%M`
  backup_directory=${directory}/${directory_month}

  if [ ! -d "${backup_directory}" ]; then
    script_error_println "${backup_directory} PATH NOT EXISTS."
    mkdir -p ${backup_directory}
  fi

  script_notify_println "Backup GitlabDB to ${backup_directory}/*gitlab_backup.tar"
  backup_database || error_exit "GitlabDB Backup Failed!! You must check out '/backup/backup.d/default.conf'."
  script_notify_println "GitlabDB Backup Successfully Done."

  sleep 7d
done
