
services:

  jupyter:
    image: 'jupyter/datascience-notebook:notebook-7.0.6'
    container_name: jupyter-notebook
    hostname: jupyter-notebook
    shm_size: 2G
    ports:
      - '18000:8888'
    environment:
      - GRANT_SUDO=yes
      - JUPYTER_TOKEN=jovyan
    volumes:
      - /opt/jupyter:/home/jovyan/work
