
services:

  mariadb_ex01:
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: rroot
    #volumes:
    #  - /docker/redmine/mysql:/var/lib/mysql
